name: Node.js CI

on:
  pull_request:
    branches: [ dev, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run tsc

      - name: Run Mocha tests With Sealights
        run: npm run test
        env:
          CI: true

      - name: Extract PR number
        id: pr
        run: echo "::set-output name=number::$(echo ${{ github.event.pull_request.number }})"

      - name: Extract short SHA
        id: sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Publish to npm
        if: github.event_name == 'pull_request'
        run: |
          PR_NUM=${{ steps.pr.outputs.number }}
          SHORT_SHA=${{ steps.sha.outputs.sha }}
          npm version prerelease --preid=pr${PR_NUM}.${SHORT_SHA} -m "ci: Publish PR$PR_NUM version [skip ci]"
          npm publish --tag pr${PR_NUM}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}